development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://localhost:9292/faye"
  secret_token: "edcaf088a15b9abc56969073779a9e37d21279c7c21294356403191f8849881e"
  signature_expiration: 3600 # one hour
